services:
  rustytube:
    build: .
    image: rustytube:latest
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SOCKET_ADDRESS=0.0.0.0
      - STATIC_DIR=/usr/local/bin/static
